[박준영]Mission 2:회원가입 엔드포인트완료
wecode-bootcamp-korea/21-Westagram-backend pull request #36
Opened 2021-05-28 01:10 UTC by Jmoon144

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- q객체 이용 or 수정 완료
- null 중복값 str로 되기때문에 해결방법을 찾지 못함.

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 validation을 함수화할 수는 없나요? (예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-05-28 09:07 UTC, jamessoun93 requested changes

2021-05-28 09:07 UTC, jamessoun93 commented on students/junyeong/user/views.py
> +
`email`, `nickname`, `phone_number` 중 하나라도 중복이면 `401`을 `return` 해주고 계신데요.
- HTTP status code 401 은 UNAUTHORIZED 의 의미라서 중복데이터가 존재한다는 의미에 리턴 status code 로는 적합하지 않습니다. 여기서는 409 를 사용할 수 있겠네요. 409에 대해 알아보세요!
- 이 3개의 if 문들을 하나의 filter 문으로 합치는 방법이 있습니다. 결국 따로따로 filter 쿼리를 날리는것보다 email 혹은 nickname 혹은 phone_number 중 하나라도 중복일 시 409 를 띄워주겠다의 의미로 장고에서 제공하는 `Q` 객체를 사용할 수 있으니 찾아보시고 적용해보세요.

2021-05-28 09:07 UTC, jamessoun93 commented on students/junyeong/user/views.py
> +
구분을 위한 빈줄은 한줄이면 충분합니다.

2021-05-28 09:07 UTC, jamessoun93 commented on students/junyeong/user/views.py
> +            )
```suggestion
            Signup.objects.create(
                nickname     = nickname,
                email        = email,
                password     = password,
                phone_number = phone_number
            )
```

2021-05-28 09:07 UTC, jamessoun93 commented on students/junyeong/user/views.py
> +            )
들여쓰기 신경써주세요.

2021-05-28 09:07 UTC, jamessoun93 commented on students/junyeong/user/views.py
> +
여기도 빈줄은 한줄씩이면 충분합니다.

2021-05-28 09:43 UTC, Jmoon144 commented on students/junyeong/user/models.py
> +from django    import db
무의식적으로 기존의것 따라하다 보니 작성이 된것같습니다. 제대로 확인못한점 반성하겠습니다.

2021-05-28 09:43 UTC, Jmoon144 commented on students/junyeong/user/models.py
> +    phone_number = models.CharField(max_length =30, null= True, unique=True)
1. kwargs부분은 수정완료했습니다. 
2. 저는 null을 중복 허용을 하고 싶고, 데이터 중복을 방지하고 싶어서 views.py에 
if Signup.objects.filter(nickname = nickname).exists():
                return JsonResponse({'message': '닉네임값이 중복되었습니다.'}, status= 401) 같이 닉네임 이메일 핸드폰 값 중복 에러를 리턴시켰습니다. 처음에는 그냥 null값이 들어가는지만 확인을 하고 제출했는데, unique를 제거하고 post해봤더니 null 값 중복이 되었습니다. 그부분은 view.py에 위처럼 작성이 되어있었기 때문에 null중복이 안되는것 같습니다. 혹시 null 제외하고 하는 좋은 방법 있으면 팁이라도 주시면 감사하겠습니다.!!!!

2021-05-28 09:46 UTC, Jmoon144 commented on students/junyeong/user/models.py
> +        db_table = 'signups'
변경완료했습니다.

2021-05-28 09:47 UTC, Jmoon144 commented on students/junyeong/user/views.py
> +class SignupListView(View):
더 정확하게 확인할수있도록 list제거하고 SignupView으로 변경완료했습니다.

2021-05-28 09:48 UTC, Jmoon144 commented on students/junyeong/user/views.py
> +
공백제거후 try:
            data = json.loads(request.body) 처럼 감싸주었습니다.

2021-05-28 09:50 UTC, Jmoon144 commented on students/junyeong/user/views.py
> +            )
들여쓰기랑 빈 줄 한줄로 수정완료했습니다.

2021-05-28 09:51 UTC, Jmoon144 commented on students/junyeong/user/views.py
> +
넵 감사합니다 수정완료했습니다!!

2021-05-28 09:51 UTC, Jmoon144 commented on students/junyeong/user/views.py
> +
수정완료했습니다.

2021-05-28 09:53 UTC, Jmoon144 commented on students/junyeong/user/models.py
> +        db_table = 'signups'
views.py import도 수정완료했습니다.

2021-05-28 10:25 UTC, Jmoon144 commented on students/junyeong/user/views.py
> +                return JsonResponse({'message': '패스워드 형식이 아닙니다.'}, status= 400)
1.거짓 값에는 빈 시퀀스 (목록, 튜플, 문자열, 사전, 집합), 모든 숫자 유형의 0 None, 및 False.라고 합니다. 그래서 if not re.search(password_regex, password):
                return JsonResponse({'message': '패스워드 형식이 아닙니다.'}, status= 400)처럼 앞에 not을 주었습니다. 

2. not이 들어가면 뒤에 패스워드가 빈값이 아니면 false라고 해서 none이랑 같은 말이기 때문에 위처럼 수정하게 되었습니다.

2021-05-28 10:27 UTC, Jmoon144 commented on students/junyeong/user/views.py
> +                return JsonResponse({'message': '패스워드 형식이 아닙니다.'}, status= 400)
1. if not re.search(password_regex, password):
                return JsonResponse({'message': '패스워드 형식이 아닙니다.'}, status= 400) 처럼 none을 제거하고 앞에 not을 입력해주었습니다.
2. none과 같이  빈 시퀀스 (목록, 튜플, 문자열, 사전, 집합), 모든 숫자 유형의 0 None, 및 False.라고 합니다 그리고 앞에 not이 들어가면 뒤에오는 패스워드가 빈값이 아니라면 false를 받는다고 합니다 . 그래서 not을 이용해서 수정하게 되었습니다.

2021-05-28 10:47 UTC, Jmoon144 commented on students/junyeong/user/models.py
> +from django    import db
전에 내용 따라하다 보니까 저도 모르게 적게 된것 같습니다. 바로 수정완료했습니다.

2021-05-28 11:11 UTC, Jmoon144 commented on students/junyeong/user/views.py
> +
q객체를 이용해 or 연산을 했습니다. 
 if User.objects.filter(
                Q(nickname = nickname) | Q(phone_number = phone_number) | Q(email = email) ):
                return JsonResponse({'message': '입력된 정보가 중복되었습니다.'}, status= 409)

이런식으로 작성을 했는데 q객체를 이용하면 조건을 줄일 수 있다는걸 알았습니다. 근데 q객체를 이용하면 줄어들지만 고객의 입장에서 어떤 정보인지 정확이 인지 할 수 없다고 생각합나디. 다른 점에서 어떤 이점이 있는지 알려주시면 감사드리겠습니다.

2021-05-28 12:28 UTC, Jmoon144 commented on students/junyeong/user/models.py
> +    phone_number = models.CharField(max_length =30, null= True, unique=True)
null값 부분은 해결을 못했습니다. 죄송합니다.

2021-05-31 07:38 UTC, jamessoun93 commented on students/junyeong/user/models.py
> +from django    import db
👍

2021-05-31 07:43 UTC, jamessoun93 commented on students/junyeong/user/models.py
> +    phone_number = models.CharField(max_length =30, null= True, unique=True)
음 준영님 제가 이부분 이해를 제대로 못했는데 저한테 오셔서 설명해주실 수 있을까요?

2021-05-31 07:43 UTC, jamessoun93 commented on students/junyeong/user/models.py
> +        db_table = 'signups'
👍

2021-05-31 07:43 UTC, jamessoun93 commented on students/junyeong/user/views.py
> +class SignupListView(View):
👍

2021-05-31 07:43 UTC, jamessoun93 commented on students/junyeong/user/views.py
> +
👍

2021-05-31 07:44 UTC, jamessoun93 commented on students/junyeong/user/views.py
> +password_regex = '^[a-zA-Z0-9!@#$%^&*()-_+={}\|\\\/].{7,}$'
이 부분 확인하셨을까요?!

2021-05-31 07:44 UTC, jamessoun93 commented on students/junyeong/user/views.py
> +                return JsonResponse({'message': 'KEY_ERROR'}, status= 400)
이 부분도요!

2021-05-31 07:44 UTC, jamessoun93 commented on students/junyeong/user/views.py
> +                return JsonResponse({'message': '패스워드 형식이 아닙니다.'}, status= 400)
👍

2021-05-31 07:48 UTC, jamessoun93 commented on students/junyeong/user/views.py
> +
넵 정확합니다. 어떤 로직이던 로직 변경에 따른 장,단점이 있는데 Q 객체를 활용해서 여러개의 if 문 내 filter 문들을 줄여준다면 데이터베이스 쿼리를 불필요하게 3번 날리지 않고 한번만 날려서 처리를 할 수 있게되는 장점이 있습니다. 하지만 말씀하신대로 클라이언트 쪽에 꼭 상세하게  어떤 부분이 잘못되었는지 말을 해줘야하는 케이스라면 따로 작성해주셔도 괜찮습니다.

2021-05-31 07:48 UTC, jamessoun93 commented on students/junyeong/user/views.py
> +
👍

2021-05-31 07:48 UTC, jamessoun93 commented on students/junyeong/user/views.py
> +
👍

2021-05-31 08:55 UTC, Jmoon144 commented on students/junyeong/user/models.py
> +    phone_number = models.CharField(max_length =30, null= True, unique=True)
승현님 말씀대로 manage.py에서 null=True 를 준 후 딕시너리 get을 주기위해 nickname     = data.get('nickname')  이런식으로 수정했더니 null값이 들어가게 되었습니다 감사합니다!

2021-06-01 01:25 UTC, jamessoun93 commented on students/junyeong/user/models.py
> +    phone_number = models.CharField(max_length =30, null= True, unique=True)
👍

2021-06-01 01:26 UTC, merged