[최승리]Mission 2_Add:User app 생성
wecode-bootcamp-korea/21-Westagram-backend pull request #37
Opened 2021-05-28 04:52 UTC by apollo058

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 엔드포인트 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 이메일 또는 핸드폰 번호로 로그인할 수 있음
- 실패시 에러 반환
- 성공시 200 OK 반환

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- CharField에서 unique=True 조건 맞추면서도 null값 줄 수 없을까요?
  blank=True, null=True 다 줘도...빈값을 중복값으로 인식해버리네요......

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-05-28 07:40 UTC, jamessoun93 requested changes

2021-05-28 07:40 UTC, jamessoun93 commented on students/seungri/user/views.py
> +            nick_name = data['nick_name']
👍👍👍

2021-05-28 07:40 UTC, jamessoun93 commented on students/seungri/user/views.py
> +            return JsonResponse({"message": "DUPLICATE_ENTRY_KEY_ERROR"}, status=400)
status 에 `=` 앞뒤로 간격 통일해주세요. 그냥 빈칸 없이 붙여서 해주시는게 제일 깔끔할 것 같네요.

2021-05-28 07:49 UTC, jamessoun93 commented
> CharField에서 unique=True 조건 맞추면서도 null값 줄 수 없을까요?
blank=True, null=True 다 줘도...빈값을 중복값으로 인식해버리네요......

해당 필드에 NULL 허용을 하고싶은데 동시에 unique 까지 주고 싶으시단 말씀이시죠? 이런 경우에는 NULL 허용을 해두고 view에서 로직으로 이미 데이터베이스에 있는 정보인지 확인하여 create 안되게끔 처리해주는 방법이 있습니다!

2021-05-28 08:25 UTC, apollo058 commented on students/seungri/user/models.py
> +from django.db.models.fields import IntegerField
수정했습니다!

2021-05-28 08:26 UTC, apollo058 commented on students/seungri/user/models.py
> +from django.db.models.fields import IntegerField
> 이 두개 import 문은 사용안하고 계셔서 불필요하니 지워주세요.

수정했습니다!

2021-05-28 08:26 UTC, apollo058 commented on students/seungri/user/views.py
> +class UserListView(View):
> 클래스명 확인해주세요. 신규 유저 등록 기능을 담고 있는 view의 클래스명으로 유저 list 를 뿌려준다는 의미의 클래스명은 알맞지 않습니다.

수정했습니다!

2021-05-28 08:27 UTC, apollo058 commented on students/seungri/user/views.py
> +                return JsonResponse({"message": "EMAIL_KEY_ERROR"}, status =  400)
> * 가독성을 위해 아래 빈줄 추가해주세요.
> * 그리고 리턴해주시는 메세지만보고 이메일 형식이 잘못되었다는걸 알기가 어렵습니다. 조금 더 명확한 메세지로 변경해주세요.

수정했습니다!

2021-05-28 08:27 UTC, apollo058 commented on students/seungri/user/views.py
> +            return JsonResponse({"message": "DUPLICATE_ENTRY_KEY_ERROR"}, status=400)
> status 에 `=` 앞뒤로 간격 통일해주세요. 그냥 빈칸 없이 붙여서 해주시는게 제일 깔끔할 것 같네요.

수정했습니다!

2021-05-28 08:27 UTC, apollo058 commented
> > CharField에서 unique=True 조건 맞추면서도 null값 줄 수 없을까요?
> > blank=True, null=True 다 줘도...빈값을 중복값으로 인식해버리네요......
> 
> 해당 필드에 NULL 허용을 하고싶은데 동시에 unique 까지 주고 싶으시단 말씀이시죠? 이런 경우에는 NULL 허용을 해두고 view에서 로직으로 이미 데이터베이스에 있는 정보인지 확인하여 create 안되게끔 처리해주는 방법이 있습니다!

감사합니다. 구현해보겠습니다.

2021-05-31 08:19 UTC, jamessoun93 requested changes

2021-05-31 08:19 UTC, jamessoun93 commented on students/seungri/user/views.py
> +            if re.compile(email_regex).match(email) == None:
- 이 부분은 compile() 없이 match 함수 하나로 합칠 수 있습니다!
- 그리고 match() 의 결과가 Truthy 한지 Falsy 한지에 따라 == None 의 비교는 불필요하게 됩니다.
- 이해가 잘 안되신다면 Truthy, Falsy value 에 대해 알아보세요!

2021-05-31 08:19 UTC, jamessoun93 commented on students/seungri/user/views.py
> +                                nick_name = nick_name)
이런식으로 조금 더 깔끔하게 정리가 가능하겠네요!
```suggestion
            User.objects.create(
                email     = email,
                password  = password,
                phone_num = phone_num,
                nick_name = nick_name
            )
```

2021-05-31 09:46 UTC, apollo058 commented on students/seungri/user/views.py
> +            if re.compile(email_regex).match(email) == None:
수정했습니다!

2021-05-31 09:47 UTC, apollo058 commented on students/seungri/user/views.py
> +                                nick_name = nick_name)
수정했습니다.

2021-06-01 01:28 UTC, merged