[박경철]:Mission2 UserApp 생성 완료
wecode-bootcamp-korea/21-Westagram-backend pull request #38
Opened 2021-05-28 05:13 UTC by pkc035

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- Mission2 요구사항 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 초기 git branch 새로 생성을 안하여 이전 초기세팅 branch 이름을 변경하여 PR한 상태입니다. 이후 mission 진행 시 유의하겠습니다.
-  user App의 .models에서 email이나 password field 작성 시 validators=[]를 사용하는게 좋은지  현재 작성된 코드와 같이 .views에서 validation을 사용하는게 좋을까요 ?? (.models에서 validators 속성을 사용해보았지만 구현 실패)
- validators.py에 구현된 validation이 올바르게 사용된건지 or 보완해야 할 부분이 있으면 확인부탁드립니다.   

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-05-28 08:09 UTC, jamessoun93 requested changes

2021-05-28 08:09 UTC, jamessoun93 commented on students/kyungchulpark/user/validators.py
> +    elif (bool(re.search('@',email))==False) or (bool(re.search('.',email))==False):
이 부분 `@` 과 `.` 유무만 판단하는게 아니고 email format 에 맞는지 정규표현식 활용해서 판단하는 방식으로 변경해보세요.

2021-05-28 08:09 UTC, jamessoun93 commented on students/kyungchulpark/user/views.py
> +                phone=phone_data)
아래와 같이 깔끔하게 정렬될 수 있도록 신경써주세요!
```suggestion
            User.objects.create(
                email    = email_data,
                password = password_data,
                nicname  = nicname_data,
                phone    = phone_data
            )
```

2021-05-28 08:09 UTC, jamessoun93 commented on students/kyungchulpark/user/views.py
> +            return JsonResponse({'message':str(e)}, status=400)
발생할 수 있는 Exception 구체적으로 핸들링할 수 있도록 변경해주세요. 이렇게 되면 어떤 Exception 이던 KeyError 가 아니라면 전부 여기서 잡게됩니다.

2021-05-28 08:11 UTC, jamessoun93 commented
> 초기 git branch 새로 생성을 안하여 이전 초기세팅 branch 이름을 변경하여 PR한 상태입니다. 이후 mission 진행 시 유의하겠습니다.

넵!

> user App의 .models에서 email이나 password field 작성 시 validators=[]를 사용하는게 좋은지 현재 작성된 코드와 같이 .views에서 validation을 사용하는게 좋을까요 ?? (.models에서 validators 속성을 사용해보았지만 구현 실패)

모델에서 validator 를 이용하려면 장고에서 제공하는 form 을 이용해야하는데 저희는 form 을 다루지 않으므로 view 에서 처리하시는 방식으로 구현해주신게 맞는 방법입니다.

> validators.py에 구현된 validation이 올바르게 사용된건지 or 보완해야 할 부분이 있으면 확인부탁드립니다.

리뷰 남겨드렸습니다.

>터미널에서 만약 (http POST localhost:8000/user/account email= password= nicname= phone= ->>> DB 저장됨) 입력 시 nicname, phone은 속성 Null = True 인 상태 입니다. 이때 email과 password는 null값이 허용되지 않고 default 값은 null로 설정되어 있어 DB에 저장이 안된다고 생각하는데 실제 TEST 시 DB에 저장된 현상이 있었습니다. email= -> 입력시 emtpy string('')으로 입력값이 들어 갔다고 생각하는데 도움 요청드립니다.

이 부분 구두로 가이드 드렸습니다!

2021-05-28 14:51 UTC, pkc035 commented on students/kyungchulpark/user/models.py
> +    phone    = models.CharField(max_length=50, null=True)
nickname, phone_number 수정했습니다.

2021-05-28 14:54 UTC, pkc035 commented on students/kyungchulpark/user/validators.py
> +        raise ValidationError('NICNAME EXIST')
null -> none 으로 수정 완료.
단순히, elif를 써도 로직 상 문제 없길래 썼습니다.

2021-05-28 14:54 UTC, pkc035 commented on students/kyungchulpark/user/validators.py
> +    elif (bool(re.search('@',email))==False) or (bool(re.search('.',email))==False):
email format 정규식에 맞게 변경하였습니다.

2021-05-31 08:27 UTC, jamessoun93 commented on students/kyungchulpark/user/models.py
> +    phone    = models.CharField(max_length=50, null=True)
👍

2021-05-31 08:59 UTC, jamessoun93 approved these changes

2021-05-31 08:59 UTC, merged