[김태우] Mission2 회원가입 엔드포인트 완료
wecode-bootcamp-korea/21-Westagram-backend pull request #39
Opened 2021-05-28 05:35 UTC by jotasic

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 회원가입 엔드포인트 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)

### 수정사항
1. User Model 생성
2. 회원 가입 로직 추가
    1. 이메일
       - 중복체크
       - 이메일 양식체크 -  정규식 사용
    2. 비밀번호 
       - 8자리 이상체크 - 정규식 사용
    3. 닉네임
       - 중복 체크
       - 빈값 및 2자리 이상인지  체크 - 정규식 사용
    4. 전화번호
       - 중복 체크
       - 빈값 및 양식 체크 - 정규식 사용

### 예외처리 관련
> 1. 추가 정보인 닉네임과 전화번호는 입력이 안 되도 처리 할 수 있도록 get()을 이용해서 받도록 함.
> 2. Key가 전달되지 않으면 {message": "KEY_ERROR} status code 400 반환 처리함.
> 3. 그외 에러는 상황에 맞는 메시지로 반환 처리함
> 4. 정상적으로 저장 시, {"message": "SUCCESS"}, status code 201 반환 처리함.
> 5. 모든 정보는 `빈 string` 이 들어오면 `잘못 입력`으로 가정하고 예외를 처리

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
1. 예외처리 관련해서 `빈 string`과 `None`을 구분하여서 처리를 해야되는 상황이 있어서 아래와 같이 작성하였습니다. 그러나 위코드 코드컨벤션 상으로는 `None` 값을 비교하는 로직 자체를 넣는 것이 위반인데 이렇게 해도 되는 건지 궁금합니다.
```python
if phone_number is not None:
```

2. views.py의 작성한 예외검사 코드의 길이가 너무 깁니다. 따로 함수로 빼는것이 나을까요?

3.  model의 field 생성시 `unique` 옵션의 경우 db상에서 `UNIQUE` 옵션과 동일한데, 어짜피 중복검사를 view에서 하기 때문에, 중복이 들어갈일이 없어서 동일하다고 생각하는데, DB성능상으로는 `UNIQUE` 옵션이 많으면 성능적으로 이점이 있을까요? 궁금해서 관련내용을 찾아봤는데, 기본키와의 비교나, 기본키가 없는 상태에서의 `UNIQUE`추가시에 이점이였습니다. model을 생성하면 기본키가 자동으로 생성되기 때문에 제가 찾은 정보와는 경우가 다르지 않나 싶습니다.
> 기본키 vs unique [🔗  참고](https://devbab.tistory.com/6)
> 기본키가 없는 상태에 unique 없을때 vs unique 있을때  [🔗  참고](https://dotnettutorials.net/lesson/performance-improvement-using-unique-keys/)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-05-28 09:45 UTC, jamessoun93 requested changes

2021-05-28 09:45 UTC, jamessoun93 commented on students/taewookim/users/models.py
> +    phone_number = models.CharField(max_length=13, unique=True, null=True, blank=False)
깔끔하게 잘 작성해주셨는데 NULL 을 허용하면서 unique=True 옵션을 함께주는게 가능할지 생각해보시고 테스트 해보시길 권장드립니다.

2021-05-28 09:45 UTC, jamessoun93 commented on students/taewookim/users/views.py
> +            phone_number = data.get('phone_number')
👍 👍 👍

2021-05-28 09:45 UTC, jamessoun93 commented on students/taewookim/users/views.py
> +                return JsonResponse({"result": "INVALIED_PASSWORD"}, status=400)
기준이 되는 정규표현식을 compile 한 뒤 match 여부를 판단할 필요없이 match 메소드에서 한번에 처리 가능합니다. 수정해보세요!

2021-05-28 09:45 UTC, jamessoun93 commented on students/taewookim/users/views.py
> +            if nickname is not None:
`if nickname is not None` 은 결국 nickname 의 Truthy value 라는 뜻일때를 말하는 것이니 `if nickname:` 으로 처리 가능합니다.

2021-05-28 09:45 UTC, jamessoun93 commented on students/taewookim/users/views.py
> +            User.objects.create(email=email, password=password, phone_number=phone_number, nickname=nickname)
```suggestion
            User.objects.create(
                email        = email, 
                password     = password, 
                phone_number = phone_number, 
                nickname     = nickname
            )
```

2021-05-28 09:45 UTC, jamessoun93 commented on students/taewookim/users/views.py
> +                return JsonResponse({"result": "DUPLICATED_EMAIL"}, status=400)
이미 존재하는 정보로 인한 실패라면 HTTP status code 409 를 활용해주세요.

2021-05-28 09:45 UTC, jamessoun93 commented on students/taewookim/users/views.py
> +                    return JsonResponse({"result": "DUPLICATED_PHONE_NUMBER"}, status=400)
- `null=True` 와 `unique=True` 가 함께 있어서 처리를 하시려다 보니 이렇게 가독성이 좋지 못한 if 문 구조가 생기게 됩니다.
- nickname 까지 validate 하는건 불필요하다고 생각해서 없애주셔도 될 것 같지만 이 부분은 기획에 따라야하는 부분이기 때문에 선택에 맡기겠습니다.
- 해당 모델 수정하면서 한번 어떻게 줄일 수 있을지 고민해보세요.

2021-05-28 09:50 UTC, jamessoun93 commented
> 예외처리 관련해서 빈 string과 None을 구분하여서 처리를 해야되는 상황이 있어서 아래와 같이 작성하였습니다. 그러나 위코드 코드컨벤션 상으로는 None 값을 비교하는 로직 자체를 넣는 것이 위반인데 이렇게 해도 되는 건지 궁금합니다.

빈 스트링으로 입력값을 받을 이유가 있어서 그렇게 처리하시는걸까요?

> views.py의 작성한 예외검사 코드의 길이가 너무 깁니다. 따로 함수로 빼는것이 나을까요?

validation 로직은 리뷰 남겨드린대로 모델 수정사항 반영해주시면 다시 한번 확인하겠습니다.

> model의 field 생성시 unique 옵션의 경우 db상에서 UNIQUE 옵션과 동일한데, 어짜피 중복검사를 view에서 하기 때문에, 중복이 들어갈일이 없어서 동일하다고 생각하는데, DB성능상으로는 UNIQUE 옵션이 많으면 성능적으로 이점이 있을까요? 궁금해서 관련내용을 찾아봤는데, 기본키와의 비교나, 기본키가 없는 상태에서의 UNIQUE추가시에 이점이였습니다. model을 생성하면 기본키가 자동으로 생성되기 때문에 제가 찾은 정보와는 경우가 다르지 않나 싶습니다.

모델에서의 unique 옵션은 말씀하신대로 pk 용도로 쓸 unique 옵션이 아닌 실제 데이터가 중복으로 들어가는것을 방지하기 위함입니다. 가장 좋은 예시로 이메일 주소가 있습니다. 지금은 우리가 서버 한개와 데이터베이스 하나로 통신을 하기때문에 한쪽에만 처리를 해줘도 별 문제가 없겠지만, 나중에는 하나의 데이터베이스를 여러 api 서버에서 호출하게 될 수도 있고, 반대로 데이터베이스가 여러개로 나뉘어 있는 경우도 있으니 아주 정확하게 양쪽에서 둘다 처리를 해주시는게 가장 좋습니다.

2021-05-28 10:00 UTC, jotasic commented
> > 예외처리 관련해서 빈 string과 None을 구분하여서 처리를 해야되는 상황이 있어서 아래와 같이 작성하였습니다. 그러나 위코드 코드컨벤션 상으로는 None 값을 비교하는 로직 자체를 넣는 것이 위반인데 이렇게 해도 되는 건지 궁금합니다.
> 
> 빈 스트링으로 입력값을 받을 이유가 있어서 그렇게 처리하시는걸까요?
```bash
http POST localhost:8000/users email="good_banan3@wecode.com" password="87654321" phone_number="" nickname=""
```
**👉 이런식으로 요청을 받을 수 있다고 생각해서, 빈 스트링에 대한 예외처리를 고민하였습니다.**

> > views.py의 작성한 예외검사 코드의 길이가 너무 깁니다. 따로 함수로 빼는것이 나을까요?
> 
> validation 로직은 리뷰 남겨드린대로 모델 수정사항 반영해주시면 다시 한번 확인하겠습니다.

**👉 네 알겠습니다!**

> > model의 field 생성시 unique 옵션의 경우 db상에서 UNIQUE 옵션과 동일한데, 어짜피 중복검사를 view에서 하기 때문에, 중복이 들어갈일이 없어서 동일하다고 생각하는데, DB성능상으로는 UNIQUE 옵션이 많으면 성능적으로 이점이 있을까요? 궁금해서 관련내용을 찾아봤는데, 기본키와의 비교나, 기본키가 없는 상태에서의 UNIQUE추가시에 이점이였습니다. model을 생성하면 기본키가 자동으로 생성되기 때문에 제가 찾은 정보와는 경우가 다르지 않나 싶습니다.
> 
> 모델에서의 unique 옵션은 말씀하신대로 pk 용도로 쓸 unique 옵션이 아닌 실제 데이터가 중복으로 들어가는것을 방지하기 위함입니다. 가장 좋은 예시로 이메일 주소가 있습니다. 지금은 우리가 서버 한개와 데이터베이스 하나로 통신을 하기때문에 한쪽에만 처리를 해줘도 별 문제가 없겠지만, 나중에는 하나의 데이터베이스를 여러 api 서버에서 호출하게 될 수도 있고, 반대로 데이터베이스가 여러개로 나뉘어 있는 경우도 있으니 아주 정확하게 양쪽에서 둘다 처리를 해주시는게 가장 좋습니다.

**👉 이런경우를 생각 못했네요. 감사합니다**

2021-05-28 11:09 UTC, jotasic commented on students/taewookim/users/models.py
> +    phone_number = models.CharField(max_length=13, unique=True, null=True, blank=False)
제 의도는 `nickname`, `phone_number` 가 추가 정보이니 입력이 안 되면 존재하지 않는 것으로 간주하여 NULL로 입력되도록  하되(null=True), 입력된 값에 대해서는 중복을 허용하지 않게 하려고(unique=True) 하였습니다

그래서 장고 쉘상으로 테스트를 하였었는데, 가능하여서 작성했습니다.

하지만 공식문서를 찾아보니 django에서는 char필드에 null를 쓰는것을 추천하지 않았고, django에서는 no data를 빈 string으로 판단하니, NULL과 겹친다는 의미 같습니다. blank, unique 둘다 true일 때만 unique의 제약을 피하기 위해서 사용한다고 써 있었습니다.

하지만 중복을 피하기 위해서  unique 옵션을 사용하였고, 빈 string을 중복으로 사용할 수 없는 상황입니다.

제가 정리한게 맞을까요?


```sql
mysql> select * from users;
+----+-------------------------+-----------+--------------+---------------+
| id | email                   | password  | nickname     | phone_number  |
+----+-------------------------+-----------+--------------+---------------+
|  1 | taewoo.kim@wecode.com   | 12345678  | 태식이       | 010-1111-1111 |
| 11 | good_apple@wecode.com   | 87654321  | 사과         | NULL          |
| 12 | good_banana@wecode.com  | 87654321  | NULL         | 010-2020-2020 |
| 13 | good_banana2@wecode.com | 87654321  | NULL         | 010-2320-2030 |
| 14 | e22ma@b.com             | eeee      | NULL         | NULL          |
| 17 | test@tt.com             | 12345678  | NULL         | NULL          |
| 18 | 3asd@asdas.com          | 123123123 | NULL         | NULL          |
| 21 | 3a11sd@asdas.com        | 123123123 | NULL         | NULL          |
+----+-------------------------+-----------+--------------+---------------+
```

[🔗 Model field reference](https://docs.djangoproject.com/en/3.2/ref/models/fields/)

2021-05-28 11:13 UTC, jotasic commented on students/taewookim/users/views.py
> +                return JsonResponse({"result": "INVALIED_PASSWORD"}, status=400)
네 match함수가 있는 것을 확인하였습니다.

![image](https://user-images.githubusercontent.com/8219812/119975765-34df3900-bff1-11eb-896a-f440ab625b64.png)

아래와 같이 수정하면 될 것 같습니다.
```python
match(PASSWORD_REGEX, password):
```

2021-05-28 11:16 UTC, jotasic commented on students/taewookim/users/views.py
> +            if nickname is not None:
> null=True 와 unique=True 가 함께 있어서 처리를 하시려다 보니 이렇게 가독성이 좋지 못한 if 문 구조가 생기게 됩니다.
> nickname 까지 validate 하는건 불필요하다고 생각해서 없애주셔도 될 것 같지만 이 부분은 기획에 따라야하는 부분이기 때문에 선택에 맡기겠습니다.
> 해당 모델 수정하면서 한번 어떻게 줄일 수 있을지 고민해보세요.

**👉 아래 코멘트 주신 내용과 연관된 내용이므로 같이 고민하도록 하겠습니다.**

2021-05-28 11:49 UTC, jotasic commented on students/taewookim/users/views.py
> +                return JsonResponse({"result": "INVALIED_PASSWORD"}, status=400)
수정완료 했습니다.

2021-05-28 11:50 UTC, jotasic commented on students/taewookim/users/views.py
> +            User.objects.create(email=email, password=password, phone_number=phone_number, nickname=nickname)
수정완료했습니다.

2021-05-28 11:50 UTC, jotasic commented on students/taewookim/users/views.py
> +                return JsonResponse({"result": "DUPLICATED_EMAIL"}, status=400)
수정완료 했습니다.

2021-05-29 04:12 UTC, jotasic commented on students/taewookim/users/views.py
> +                    return JsonResponse({"result": "DUPLICATED_PHONE_NUMBER"}, status=400)
- 이 부분은 아래처럼 if문을 합치려고 처음에 생각하였으나, 여전히 가독성이 좋지 못하였습니다.
```python                
if phone_number is not None and not re.compile(PHONE_REGEX).match(phone_number):                    
  return JsonResponse({"result": "INVALIED_PHONE_NUMBER"}, status=400)
```

- 또한 제가 너무 제약조건을 많이 건다는 생각도 들었습니다.
   1. null=True 
   2. unique=True
   3. 빈 문자열 입력시 예외처리

- 그래서 이 3중에서 우선순위가 떨어지는 부분을 생각하였고, 제 생각에는 `null 허용을 하지 않는 쪽`으로 가닥을 잡았으며,
 `phone_number`, `nickname`을 `null=True`를 제거하였습니다.

- 결론적으로는 null을 허용 안하므로써, 무조건 값이 들어오기 때문에, None인지 아닌지 검사하는 if문을 제거할 수 있었습니다.

- 닉네임 까지 validate을 하려는 이유는 빈 문자열을 체크하려는 의도였습니다. 단순히 `len(nickname) == 0` 이런 느낌으로 체크할 수 도 있겠지만 코드의 통일성을 위해 정규표현식을 사용하였습니다.

2021-05-29 04:13 UTC, jotasic commented on students/taewookim/users/views.py
> +            if nickname is not None:
해당 필드들에 null을 허용하지 않게 수정하여 바깥에 있는 if문을 제거할 수 있었습니다.

2021-05-31 09:03 UTC, jamessoun93 commented on students/taewookim/users/models.py
> +    phone_number = models.CharField(max_length=13, unique=True, null=True, blank=False)
- 넵 정확하게 이해하셨습니다. 저희는 nickname 과 phone_number 를 아예 받지 않아도 데이터베이스에 create 하는데 문제가 없게끔 하기위해 NULL 을 NO DATA 라는 의미로 쓰기 때문에 사용하시는데 전혀 문제가 없습니다. 
- 훌륭한 정리 감사합니다 👍

2021-05-31 09:03 UTC, jamessoun93 commented on students/taewookim/users/views.py
> +                return JsonResponse({"result": "INVALIED_PASSWORD"}, status=400)
👍

2021-05-31 09:04 UTC, jamessoun93 commented on students/taewookim/users/views.py
> +            User.objects.create(email=email, password=password, phone_number=phone_number, nickname=nickname)
👍

2021-05-31 09:05 UTC, jamessoun93 commented on students/taewookim/users/views.py
> +                    return JsonResponse({"result": "DUPLICATED_PHONE_NUMBER"}, status=400)
👍

2021-05-31 09:18 UTC, jamessoun93 approved these changes
LGTM 👍

2021-05-31 09:19 UTC, merged