[이아란] Mission:2 회원가입 엔드포인트 완료
wecode-bootcamp-korea/21-Westagram-backend pull request #54
Opened 2021-05-29 08:05 UTC by araaaaan

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 이메일 형식 확인
- 이메일, 전화번호, 닉네임 중복값 확인
- 비밀번호 8자 이상 입력 확인

		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 이메일 형식 확인을 위해 정규식 사용 
- 가입 실패시 에러 반환
- 기존 데이터 중복시 에러 반환
- 성공시 201 반환

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 코드를 더 간단하게 쓸 수 없을까요?
- validator를 사용하기 위해 validation.py파일을 따로 만들어봤는데 어떻게 사용하는지 모르겠습니다
- 데이터를 지웠다 넣었다 해서 PK가 1번부터 시작하지 않는데 괜찮은가요?

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-05-31 06:06 UTC, jamessoun93 requested changes

2021-05-31 06:06 UTC, jamessoun93 commented on students/aranlee/user/views.py
> +
이런식으로 내가 모르는 exception 이 발생했을때 모두 처리해줄 수 있게끔 처리하는 방식은 좋지 않습니다. 어떤 exception 이 발생하는지 명확히 모르겠다면 차라리 해당 exception 이 발생해서 500으로 처리가 된 뒤 명확하게 이럴 때 발생하는구나를 확인하시고 후에 exception 처리를 해주시는 방법이 좋습니다.

2021-05-31 06:08 UTC, jamessoun93 commented
> 코드를 더 간단하게 쓸 수 없을까요?

코드를 더 간단하게 줄여보고자 하는 의지 넘 좋습니다 👍 
하지만 지금은 어떤부분에서 줄일 수 있는지를 모르기때문에 당연한 부분이라, 리뷰 반영하시면서 조금씩 반복되는 코드가 줄어드는 것을 체감하실 수 있을거에요!

> validator를 사용하기 위해 validation.py파일을 따로 만들어봤는데 어떻게 사용하는지 모르겠습니다

my_settings.py 에서 변수 선언하여 필요한 파일에서 import 해온 방식이랑 정확하게 일치합니다. 해당 파일에 함수를 선언해놓고 필요한곳에서 해당 함수를 import 해서 호출하면 됩니다.

> 데이터를 지웠다 넣었다 해서 PK가 1번부터 시작하지 않는데 괜찮은가요?

넵 전혀 상관없습니다.

2021-06-01 04:39 UTC, araaaaan commented on students/aranlee/user/models.py
> +
확인했습니다!

2021-06-01 04:39 UTC, araaaaan commented on students/aranlee/user/models.py
> +    user_email = models.CharField(max_length=40, default=None, unique=True)
바꿨습니다!

2021-06-01 04:40 UTC, araaaaan commented on students/aranlee/user/models.py
> +    password   = models.CharField(max_length=30, default=None)
모르고 썼네요... 공부했습니다😅

2021-06-01 04:40 UTC, araaaaan commented on students/aranlee/user/urls.py
> +  path('/signup', SignUpView.as_view())
수정했습니다

2021-06-01 04:41 UTC, araaaaan commented on students/aranlee/user/views.py
> +
넵

2021-06-01 04:42 UTC, araaaaan commented on students/aranlee/user/views.py
> +            if not re.match (validation_email, user_email)  :
수정 했습니다

2021-06-01 04:42 UTC, araaaaan commented on students/aranlee/user/views.py
> +                return JsonResponse({'message': 'NICK_NAME_EXISTS'}, status=400)
수정해서 적용했습니다!

2021-06-01 04:43 UTC, araaaaan commented on students/aranlee/user/views.py
> +                return JsonResponse({'message': 'SUCCESS'} , status=201)
수정했습니다 !!!

2021-06-01 04:44 UTC, araaaaan commented on students/aranlee/user/views.py
> +
넵 확인했습니다

2021-06-01 04:44 UTC, araaaaan commented on students/aranlee/user/views.py
> +
구분을 위한 빈줄...! 완전 확인했습니다

2021-06-02 01:09 UTC, merged