[송준] Mission 3: 로그인 엔드포인트 완료
wecode-bootcamp-korea/21-Westagram-backend pull request #62
Opened 2021-06-01 03:03 UTC by riassuc

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 엔드포인트 구현(예시)
- 로그인 엔드포인트 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 이메일 또는 핸드폰 번호로 로그인할 수 있음
- 실패시 에러 반환
- 성공시 200 OK 반환, jwt 생성

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 validation을 함수화할 수는 없나요? (예시) 
- 회원가입을 할때 bcrypt의 gensalt로 비밀번호를  그냥 해싱하지 않고 소금을 더 넣어서 복잡하게 해싱을 하는데
  제가 생각했을때는 mysalt = bcrypt.gensalt() 이렇게 무작위로 생성한 소금을 변수에 저장해서
  로그인을 할때 db에 비밀번호와 입력받은 비밀번호를 비교할때 그 mysalt를 사용해서 해시된 암호를 비교할 줄 알았습니다.
  (인증/인가 세션에서 jwt 사용할때 서버 시크릿키로 확인 하는것처럼) 
  근데 그런거 없이도 그냥 암호가 맞는지 체크가 되는데 어떻게 그럴수가 있는지 모르겠습니다.
  무작위로 생성한 소금이 뭔지 몰라도 체크가 된다면 보안의 효과가 없는거 같다고 생각되어서 혼란스럽습니다. 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-06-02 02:32 UTC, jamessoun93 requested changes

2021-06-02 02:32 UTC, jamessoun93 commented on students/junsong/user/views.py
> +            password_crypt = bcrypt.hashpw(password.encode('utf-8'), bcrypt.gensalt()).decode('utf-8')
👍

2021-06-02 02:32 UTC, jamessoun93 commented on students/junsong/user/views.py
> +                password = password_crypt,
👍

2021-06-02 02:32 UTC, jamessoun93 commented on students/junsong/user/views.py
> +                    return JsonResponse({"message": "SUCCESS", "token": token}, status=200)
if 문이 이런식으로 nesting 될 경우 가독성이 많이 떨어지게 됩니다. 조건을 반대로 걸어준다면 조금 더 깔끔해지겠네요! 수정해보세요~

2021-06-02 02:36 UTC, jamessoun93 commented
> 회원가입을 할때 bcrypt의 gensalt로 비밀번호를 그냥 해싱하지 않고 소금을 더 넣어서 복잡하게 해싱을 하는데
제가 생각했을때는 mysalt = bcrypt.gensalt() 이렇게 무작위로 생성한 소금을 변수에 저장해서
로그인을 할때 db에 비밀번호와 입력받은 비밀번호를 비교할때 그 mysalt를 사용해서 해시된 암호를 비교할 줄 알았습니다.
(인증/인가 세션에서 jwt 사용할때 서버 시크릿키로 확인 하는것처럼)
근데 그런거 없이도 그냥 암호가 맞는지 체크가 되는데 어떻게 그럴수가 있는지 모르겠습니다.
무작위로 생성한 소금이 뭔지 몰라도 체크가 된다면 보안의 효과가 없는거 같다고 생각되어서 혼란스럽습니다.

bcrypt.checkpw() 메소드에 대한 이해가 아직 안되셔서 헷갈리시는 것 같습니다. 암호화된 비밀번호에는 이미 salt 값이 포함되어 있기때문에 해당 salt 값을 활용해서 checkpw 메소드에서 비교를 하게 됩니다.

2021-06-02 06:57 UTC, riassuc commented on students/junsong/user/views.py
> +                    return JsonResponse({"message": "SUCCESS", "token": token}, status=200)
넵 해보겠습니다!

2021-06-02 07:39 UTC, jamessoun93 requested changes

2021-06-02 07:39 UTC, jamessoun93 commented on students/junsong/user/views.py
> +                return JsonResponse({"message": "SUCCESS", "token": token}, status=200)
자, 존재하지 않는 유저 정보인 경우와, 비밀번호가 틀린 경우는 완전히 다른 경우겠죠? 그래서 각각 다른 로직으로 작성해주시는게 좋습니다. email 존재여부 확인하는 if 문이 있고, 해당 if 문의 return 문을 만나지 않았다면 아래 if 문에서 비밀번호가 일치하지 않는 경우만 걸러주는 if 문이 있으면 되겠죠? 그리고 아무 if 조건에도 걸리지 않는다면 정상적으로 jwt 를 발급하면 됩니다. 그래서 if 문에는 안되는 조건만 걸어주시는게 깔끔합니다!

2021-06-03 01:16 UTC, jamessoun93 approved these changes

2021-06-03 01:16 UTC, merged