[최승리] Mission3 : 로그인 엔드포인트 완료
wecode-bootcamp-korea/21-Westagram-backend pull request #68
Opened 2021-06-01 05:37 UTC by apollo058

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 엔드포인트 구현
- password 암호화 구현
- token 생성 및 return
		 
## 수정 사항들 자세한 내용
- 이메일 또는 핸드폰 번호로 로그인할 수 있음
- password 암호화 저장
- 로그인 성공시 token return
- 실패시 에러 반환
- 성공시 200 OK 반환

## 기타 질문 및 특이 사항

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-06-02 09:48 UTC, jamessoun93 requested changes

2021-06-02 09:48 UTC, jamessoun93 commented on students/seungri/user/views.py
> +                password  = bcrypt.hashpw(password.encode('utf-8'), bcrypt.gensalt()).decode('utf-8'),
👍

2021-06-02 09:48 UTC, jamessoun93 commented on students/seungri/user/views.py
> +            db_password = db_password.encode('utf-8')
이정도는 합쳐주시는게 더 깔끔할 것 같네요.
```suggestion
            db_password = login_user.password.encode('utf-8')
```

2021-06-02 09:48 UTC, jamessoun93 commented on students/seungri/user/views.py
> +            token     = jwt.encode(user, SECRET_KEY, ALGORITHM)
이 부분도 굳이 따로 변수를 생성할 필요까지는 없어보입니다.
```suggestion
            token     = jwt.encode({"user_id" : login_user.id}, SECRET_KEY, ALGORITHM)
```

2021-06-02 09:48 UTC, jamessoun93 commented on students/seungri/user/views.py
> +            token_str = token.decode('utf-8')
이 부분 에러 발생하지 않나요? 위에서 발행된 jwt의 타입이 뭘까요? byte 인 경우 str 로 변환해주기위해 decode 를 사용하는데 다시한번 확인바랍니다.

2021-06-03 01:09 UTC, apollo058 commented on students/seungri/user/views.py
> +            db_password = db_password.encode('utf-8')
수정했습니다!

2021-06-03 01:09 UTC, apollo058 commented on students/seungri/user/views.py
> +            token     = jwt.encode(user, SECRET_KEY, ALGORITHM)
수정했습니다!

2021-06-03 01:10 UTC, apollo058 commented on students/seungri/user/views.py
> +            token_str = token.decode('utf-8')
제가 PyJWT 1.7버전 사용하고 있었습니다! 업데이트하고 코드 수정했습니다!

2021-06-03 01:17 UTC, jamessoun93 commented on students/seungri/user/views.py
> +            token_str = token.decode('utf-8')
👍

2021-06-03 01:17 UTC, merged