[장동국]Mission: 3 로그인 엔드포인트 완료
wecode-bootcamp-korea/21-Westagram-backend pull request #83
Opened 2021-06-02 12:41 UTC by JangDongGuk

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약

- 로그인 엔드포인트 구현
- 비밀번호 암호화(bcrypt)
- 로그인 성공시 토큰발행
		 
## 수정 사항들 자세한 내용

## 기타 질문 및 특이 사항

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-06-03 06:01 UTC, jamessoun93 requested changes

2021-06-03 06:01 UTC, jamessoun93 commented on students/dongguk/users/views.py
> +                return JsonResponse({'message': 'INVALID_USER'}, status=401)
이 부분 재확인해주세요. 반대가 되어야할 것 같네요.

2021-06-03 09:43 UTC, JangDongGuk commented on students/dongguk/users/views.py
> +                return JsonResponse({'message': 'INVALID_USER'}, status=401)
네 수정했습니다.

2021-06-03 10:44 UTC, jamessoun93 requested changes

2021-06-03 10:44 UTC, jamessoun93 commented on students/dongguk/users/views.py
> +                return JsonResponse({'message': 'SUCCESS', 'user_token' : jwt.encode({'id': user.id}, SECRET_KEY, ALGORITHM)}, status=200)
만약 이렇게만 두면 비밀번호 체크에 실패했을시엔 어떻게 되는걸까요?

2021-06-03 13:25 UTC, JangDongGuk commented on students/dongguk/users/views.py
> +                return JsonResponse({'message': 'SUCCESS', 'user_token' : jwt.encode({'id': user.id}, SECRET_KEY, ALGORITHM)}, status=200)
네 runserver을 통한결과 서버오류 500이 나와   return값을 다시 success를 주어줄라 했지만 if문의 코드의 해석한 내용과 주어지는 return값이 말이 안맞는 것 같아 if문에 not을 추가하였고, return값은 status=401 나오도록 구성하였습니다.

2021-06-04 06:39 UTC, jamessoun93 commented on students/dongguk/users/views.py
> +                return JsonResponse({'message': 'SUCCESS', 'user_token' : jwt.encode({'id': user.id}, SECRET_KEY, ALGORITHM)}, status=200)
👍

2021-06-04 06:39 UTC, merged